import type { ReaderSettings } from "./types";

export const DEFAULT_SETTINGS: ReaderSettings = {
  fontSize: 19.25,
  lineHeight: 1.88,
  letterSpacing: 0,
  paragraphSpacing: 1.34,
  boldRatio: "low",
  customBoldRatio: 0.36,
  bionicWeight: 525,
  bodyFontWeight: 400,
  fontFamily: "Charter, \"Bitstream Charter\", \"TsangerJinKai\", \"Tsanger JinKai\", \"Iowan Old Style\", \"Source Serif 4\", \"Noto Serif\", \"Songti SC\", \"Yu Mincho\", Georgia, serif",
  theme: "sepia",
  pageWidthMode: "px",
  pageWidth: 660,
  pageWidthVw: 90,
  pageWidthCh: 64,
  readingPadding: 64,
  textIndent: 0,
  textAlign: "left",
  ttsProvider: "edge",
  edgeVoice: "en-US-EmmaMultilingualNeural",
  edgeRate: 1,
  edgePitch: 0,
  azureApiKey: "",
  azureRegion: "eastus2",
  azureVoice: "en-US-Ava:DragonHDLatestNeural",
  elevenApiKey: "",
  elevenVoiceId: "EXAVITQu4vr4xnSDxMaL",
  elevenModelId: "eleven_v3",
  elevenLanguageCode: "en",
  elevenOutputFormat: "mp3_44100_128",
  elevenStability: 0.5,
  elevenSimilarityBoost: 0.75,
  elevenStyle: 0,
  elevenUseSpeakerBoost: true,
  elevenSpeed: 1,
  elevenSeed: null,
  elevenApplyTextNormalization: "auto",
  elevenEnableLogging: true,
  elevenOptimizeStreamingLatency: null,
  elevenWordSyncHighlight: true,
  geminiApiKey: "",
  geminiModel: "gemini-2.5-flash-preview-tts",
  geminiVoiceName: "Kore",
  geminiStylePrompt: "",
  geminiUseMultiSpeaker: false,
  geminiSpeaker1Name: "Speaker1",
  geminiSpeaker1VoiceName: "Kore",
  geminiSpeaker2Name: "Speaker2",
  geminiSpeaker2VoiceName: "Puck",
  aiExplainEnabled: true,
  aiLongPressMs: 520,
  aiContextChars: 1800,
  deepseekApiKey: "",
  deepseekModel: "deepseek-v4-flash",
  deepseekMaxTokens: 900,
  autoPlayNext: true,
  ttsConcurrency: 4,
  ttsRate: 1,
  ttsVolume: 1,
  ttsPauseMs: 400,
  readingMode: "audio",
};

export const SETTINGS_STORAGE_KEY = "bionicReaderSettings";
